<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="RegistrationType">
    <xs:annotation>
      <xs:documentation>Тип регистрации НП в ИС ЭСФ</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="ENTERPRISE">
        <xs:annotation>
          <xs:documentation>Юридическое лицо</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="ENTREPRENEUR">
        <xs:annotation>
          <xs:documentation>Индивидуальный предприниматель</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="INDIVIDUAL">
        <xs:annotation>
          <xs:documentation>Физическое лицо</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>
