import { useEffect, useRef, useState } from "react";
import { AI_MANAGER_GOALS, getAiSetupScenarios, type AiManagerDraft, type AiManagerGoal, type AiSetupQualityRun, type AiSetupState } from "@creolab/contracts";
import { api } from "../lib/api";
import { useLocale } from "../lib/session";
import { InlineFeedback } from "./InlineFeedback";

export function AiGoalPicker({ draft, onChange }: { draft: AiManagerDraft; onChange: (value: AiManagerDraft["conversation"]) => void }) {
  const locale = useLocale(); const lang = locale === "kk" ? "kk" : locale === "en" ? "en" : "ru";
  const t = (ru: string, kk: string, en: string) => ({ ru, kk, en })[lang];
  const [pending, setPending] = useState<AiManagerGoal | null>(null);
  function apply(goal: AiManagerGoal, overwrite: boolean) {
    const next = { ...draft.conversation, goalPreset: goal.id };
    for (const key of ["goal", "questions", "completion", "successCriteria"] as const) if (overwrite || !next[key]?.trim()) next[key] = goal[key][lang];
    onChange(next); setPending(null);
  }
  return <div className="ai-setup-goals"><h4>{t("Начните с готовой цели", "Дайын мақсаттан бастаңыз", "Start with a ready-made goal")}</h4><p className="ai-setup-help">{t("Выберите результат для клиента. Затем уточните вопросы и критерии под свой бизнес.", "Клиент нәтижесін таңдаңыз. Содан кейін сұрақтар мен өлшемдерді бизнесіңізге бейімдеңіз.", "Choose the customer outcome, then tailor the questions and success criteria to your business.")}</p><div className="ai-setup-goal-grid">{AI_MANAGER_GOALS.filter(goal => goal.roles.includes(draft.primaryRole)).map(goal => <button key={goal.id} type="button" aria-pressed={draft.conversation.goalPreset === goal.id} onClick={() => ["goal", "questions", "completion", "successCriteria"].some(key => String(draft.conversation[key as keyof typeof draft.conversation] || "").trim()) ? setPending(goal) : apply(goal, false)}><b>{goal.label[lang]}</b><small>{goal.goal[lang]}</small></button>)}<button type="button" aria-pressed={draft.conversation.goalPreset === "custom"} onClick={() => { onChange({ ...draft.conversation, goalPreset: "custom" }); setPending(null); }}><b>{t("Своя цель", "Өз мақсатыңыз", "Custom goal")}</b><small>{t("Опишите нужный результат ниже", "Қажетті нәтижені төменде сипаттаңыз", "Describe the desired outcome below")}</small></button></div>
    {pending && <div className="ai-setup-guidance" role="alert"><b>{pending.label[lang]}</b><p>{t("В сценарии уже есть ваши ответы. Как применить заготовку?", "Сценарийде жауаптарыңыз бар. Үлгіні қалай қолданамыз?", "Your flow already contains answers. How should this template be applied?")}</p><div className="ai-setup-actions"><button className="btn secondary" onClick={() => apply(pending, false)}>{t("Только пустые поля", "Тек бос өрістер", "Fill empty fields")}</button><button className="btn secondary" onClick={() => apply(pending, true)}>{t("Заменить 4 поля сценария", "Сценарийдің 4 өрісін ауыстыру", "Replace the 4 flow fields")}</button><button className="btn secondary" onClick={() => setPending(null)}>{t("Отмена", "Болдырмау", "Cancel")}</button></div></div>}
  </div>;
}

function ScenarioReview({ run, revision, onState, onBusy }: { run: AiSetupQualityRun; revision: number; onState: (state: AiSetupState) => void; onBusy: (busy: boolean) => void }) {
  const locale = useLocale(); const t = (ru: string, kk: string, en: string) => locale === "kk" ? kk : locale === "en" ? en : ru;
  const [review, setReview] = useState({ accurate: run.review?.accurate ?? false, onGoal: run.review?.onGoal ?? false, appropriate: run.review?.appropriate ?? false, notes: run.review?.notes || "" });
  const [error, setError] = useState("");
  async function save() { onBusy(true); setError(""); try { onState(await api.reviewAiManagerSetup({ revision, runId: run.id, ...review })); } catch (err) { setError((err as Error).message); } finally { onBusy(false); } }
  return <div className="ai-setup-test-review"><b>{t("Ваша оценка диалога", "Диалогты бағалауыңыз", "Your conversation review")}</b><p className="ai-setup-help">{t("Отмечайте только проверенное. Если ответ не подходит, сохраните замечание и уточните анкету.", "Тек тексерілгенді белгілеңіз. Жауап сәйкес болмаса, ескерту сақтап, анкетаны нақтылаңыз.", "Check only what you have verified. If the reply is unsuitable, save your notes and refine the questionnaire.")}</p>{([
    ["accurate", t("Факты, цены и условия верны; выдумок нет", "Дерек, баға мен шарттар дұрыс; ойдан мәлімет жоқ", "Facts, prices and terms are correct; no invented claims")],
    ["onGoal", t("Ожидаемый результат сценария достигнут", "Сценарийдің күтілген нәтижесіне жетті", "The scenario's expected outcome was reached")],
    ["appropriate", t("Язык, тон и передача сотруднику уместны", "Тіл, мәнер және қызметкерге беру орынды", "Language, tone and staff handoff are appropriate")],
  ] as const).map(([key, label]) => <label key={key} className="ai-setup-check"><input type="checkbox" checked={review[key]} onChange={e => setReview({ ...review, [key]: e.target.checked })} />{label}</label>)}<label className="ai-setup-field">{t("Что улучшить (необязательно)", "Нені жақсарту керек (міндетті емес)", "Notes for improvement (optional)")}<textarea maxLength={2000} rows={2} value={review.notes} onChange={e => setReview({ ...review, notes: e.target.value })} /></label>{error && <InlineFeedback className="error">{error}</InlineFeedback>}<button className="btn secondary" onClick={() => void save()}>{t("Сохранить оценку", "Бағалауды сақтау", "Save review")}</button></div>;
}

export function AiSetupQualityChecks({ state, disabled, onState, onBusy }: { state: AiSetupState; disabled: boolean; onState: (state: AiSetupState) => void; onBusy: (busy: boolean) => void }) {
  const locale = useLocale(); const lang = locale === "kk" ? "kk" : locale === "en" ? "en" : "ru";
  const t = (ru: string, kk: string, en: string) => ({ ru, kk, en })[lang];
  const scenarios = getAiSetupScenarios(state.draft);
  const [selected, setSelected] = useState(scenarios[0].id), [input, setInput] = useState(scenarios[0].message[lang]), [error, setError] = useState("");
  const [continuing, setContinuing] = useState(false);
  const resultRef = useRef<HTMLDivElement>(null), composeRef = useRef<HTMLTextAreaElement>(null);
  const scenario = scenarios.find(item => item.id === selected) || scenarios[0];
  const run = state.quality?.runs.find(item => item.scenarioId === scenario.id);
  useEffect(() => { if (run) { resultRef.current?.scrollIntoView({ block: "start", behavior: "instant" }); resultRef.current?.focus({ preventScroll: true }); } }, [run?.id]);
  useEffect(() => { if (continuing) { composeRef.current?.scrollIntoView({ block: "center", behavior: "instant" }); composeRef.current?.focus({ preventScroll: true }); } }, [continuing]);
  const passed = (run?: AiSetupQualityRun) => Boolean(run?.review?.accurate && run.review.onGoal && run.review.appropriate);
  const count = scenarios.filter(item => item.required && passed(state.quality?.runs.find(run => run.scenarioId === item.id))).length;
  function select(id: string) { const target = scenarios.find(item => item.id === id)!; setSelected(id); setInput(target.message[lang]); setContinuing(false); setError(""); }
  async function test() {
    if (disabled || !input.trim()) return;
    onBusy(true); setError("");
    const messages = continuing && run ? [...run.messages, { role: "assistant" as const, content: run.reply }, { role: "user" as const, content: input.trim() }] : [{ role: "user" as const, content: input.trim() }];
    try { await api.previewAiManagerSetup({ revision: state.revision, scenarioId: scenario.id, messages }); onState(await api.aiManagerSetup()); setInput(""); setContinuing(false); }
    catch (err) { setError((err as Error).message); } finally { onBusy(false); }
  }
  return <div className="ai-setup-quality"><div className="ai-setup-quality-heading"><div><h4>{t("Проверка перед запуском", "Іске қосар алдындағы тексеру", "Pre-launch checks")}</h4><p>{t("Пройдите короткие сценарии и оцените ответы. В основных сценариях продолжайте разговор до выбранного результата.", "Қысқа сценарийлерден өтіп, жауаптарды бағалаңыз. Негізгі сценарийлерде таңдалған нәтижеге дейін сөйлесіңіз.", "Try these scenarios and review the replies. Continue the main scenarios until the chosen outcome is reached.")}</p></div><span className="badge">{count} / {scenarios.filter(item => item.required).length}</span></div><p className="ai-setup-help">{t("Клиентам ничего не отправляется. Тесты используют AI-кредиты. Изменение анкеты или модели требует новой проверки; оценка владельца не гарантирует отсутствие всех ошибок.", "Клиентке хабар жіберілмейді. Сынақтар AI-кредит жұмсайды. Анкета не модель өзгерсе, қайта тексеру керек; иесінің бағасы барлық қатенің жоқтығына кепіл емес.", "No customer messages are sent. Tests use AI credits. Questionnaire or model changes require new checks; owner review does not guarantee error-free replies.")}</p><div className="ai-setup-scenario-tabs" role="group" aria-label={t("Проверочные сценарии", "Тексеру сценарийлері", "Test scenarios")}>{scenarios.map(item => <button type="button" key={item.id} aria-pressed={scenario.id === item.id} onClick={() => select(item.id)}>{passed(state.quality?.runs.find(run => run.scenarioId === item.id)) ? "✓ " : ""}{item.title[lang]}{!item.required && <small>{t("Дополнительно", "Қосымша", "Optional")}</small>}</button>)}</div>
    <div className="ai-setup-guidance"><b>{t("Ожидаемое поведение", "Күтілетін әрекет", "Expected behavior")}</b><p>{scenario.expectation[lang]}</p></div>
    {run && <><div ref={resultRef} tabIndex={-1} className="ai-setup-chat-log" role="log" aria-label={t("Результат сценария", "Сценарий нәтижесі", "Scenario result")}>{[...run.messages, { role: "assistant", content: run.handoff ? t("ИИ передал бы вопрос сотруднику.", "ЖИ сұрақты қызметкерге берер еді.", "AI would hand this question to staff.") : run.reply }].map((item, i) => <p className={`ai-setup-chat-message ${item.role === "user" ? "is-user" : ""}`} key={i}><small>{item.role === "user" ? t("Клиент", "Клиент", "Customer") : "AI"}</small>{item.content}</p>)}</div>{run.handoffSummary && <div className="ai-setup-guidance"><b>{t("Сводка для сотрудника", "Қызметкерге түйін", "Staff summary")}</b><p>{run.handoffSummary.request}</p>{!!run.handoffSummary.collected.length && <ul>{run.handoffSummary.collected.map((fact, i) => <li key={i}>{fact}</li>)}</ul>}<p>{run.handoffSummary.nextStep}</p></div>}<div className="ai-setup-actions">{!run.handoff && run.messages.length < 19 && <button className="btn secondary" disabled={disabled} onClick={() => { setContinuing(true); setInput(""); }}>{t("Продолжить этот диалог", "Осы диалогты жалғастыру", "Continue this conversation")}</button>}<button className="btn secondary" disabled={disabled} onClick={() => { setContinuing(false); setInput(scenario.message[lang]); }}>{t("Проверить заново", "Қайта тексеру", "Test again")}</button></div><ScenarioReview key={`${run.id}:${run.review?.reviewedAt || "new"}`} run={run} revision={state.revision} onState={onState} onBusy={onBusy} />{run.review && <p className="ai-setup-help" role="status">{passed(run) ? t("Вы подтвердили этот сценарий.", "Бұл сценарийді растадыңыз.", "You approved this scenario.") : t("Нужна доработка. Уточните анкету и повторите проверку.", "Жетілдіру керек. Анкетаны нақтылап, қайта тексеріңіз.", "Needs improvement. Refine the questionnaire and test again.")}</p>}</>}
    <div className="ai-setup-test-compose"><label className="ai-setup-field">{continuing ? t("Следующее сообщение клиента", "Клиенттің келесі хабары", "Next customer message") : t("Сообщение для нового теста", "Жаңа сынақ хабары", "Message for a new test")}<textarea ref={composeRef} rows={3} value={input} maxLength={4000} disabled={disabled} onChange={e => setInput(e.target.value)} /></label>{error && <InlineFeedback className="error">{error}</InlineFeedback>}<button className="btn" disabled={disabled || !input.trim()} onClick={() => void test()}>{t("Получить ответ ИИ", "ЖИ жауабын алу", "Get AI reply")}</button></div>
    {disabled && <p className="ai-setup-help">{t("Для проверки сохраните анкету, исправьте обязательные поля и убедитесь, что тариф включает ИИ-менеджера.", "Тексеру үшін анкетаны сақтап, міндетті өрістерді түзетіңіз және тарифте ЖИ-менеджер барын тексеріңіз.", "Save the questionnaire, complete required fields and ensure your plan includes AI manager.")}</p>}
  </div>;
}
