import { useState } from "react";

export type IntegrationHelpKind =
  | "website_form" | "webhook_api" | "google_calendar" | "google_forms" | "google_email"
  | "meta_instagram" | "meta_leads" | "tiktok" | "telegram_bot" | "whatsapp" | "esf" | "employee_telegram";

const CONTENT: Record<IntegrationHelpKind, { title: string; intro: string; before: string[]; steps: string[]; check: string; trouble: string[] }> = {
  website_form: { title: "Форма сайта", intro: "Заявки отправляются на публичный адрес CRM и появляются в разделе «Заявки».", before: ["Доступ к HTML-коду сайта или настройкам конструктора", "Телефон клиента в форме сделайте обязательным"], steps: ["Откройте карточку «Форма сайта» и скопируйте адрес для заявок.", "Для HTML укажите этот адрес в action формы с method=POST. Имена полей: name, phone, company, message, pageUrl.", "Для JavaScript отправляйте JSON с заголовком Content-Type: application/json и уникальным X-Submission-Id.", "Для Tilda откройте Настройки сайта → Формы → Webhook и вставьте адрес.", "Отправьте тестовую заявку и проверьте раздел «Заявки»."], check: "Нажмите «Проверить подключение». Затем проверьте, что тестовая заявка имеет источник «Форма сайта».", trouble: ["400 — проверьте имя поля phone и формат JSON.", "Дубликаты — не повторяйте X-Submission-Id."] },
  webhook_api: { title: "Webhook / API", intro: "Внешняя система может передавать заявки в CRM через защищённый endpoint.", before: ["Публичный HTTPS-адрес CRM", "Система-источник, умеющая отправлять POST JSON"], steps: ["Скопируйте endpoint и секрет интеграции из карточки Webhook / API.", "Передавайте name, phone, company, message, pageUrl и внешний идентификатор события.", "Подписывайте запрос секретом из инструкции endpoint и сохраняйте ответ CRM.", "Сначала включите тестовый режим и отправьте пробное событие.", "После проверки отключите тестовый режим."], check: "Проверьте журнал входящих событий: статус должен быть PROCESSED, а заявка — отображаться в CRM.", trouble: ["401/403 — неверная подпись или секрет.", "Дубликат — внешний идентификатор события уже использовался."] },
  google_calendar: { title: "Google Calendar", intro: "Встречи и изменения встреч из CRM синхронизируются с выбранным календарём Google.", before: ["Администратор BasQar должен настроить Google OAuth", "Доступ к нужному Google-аккаунту"], steps: ["Нажмите «Подключить через Google».", "Войдите в нужный аккаунт и разрешите доступ к календарю.", "Укажите ID календаря; значение primary использует основной календарь.", "Вернитесь в CRM и нажмите «Синхронизировать».", "Создайте тестовую встречу в CRM и проверьте её в Google Calendar."], check: "После синхронизации у подключения должен быть статус «Подключено», а тестовая встреча — внешний идентификатор Google.", trouble: ["OAuth недоступен — администратору нужно проверить Client ID/Secret и Redirect URI.", "Событие не видно — проверьте ID календаря и часовой пояс."] },
  google_forms: { title: "Google Forms", intro: "Новые ответы Google Forms превращаются в заявки CRM.", before: ["Доступ к форме и Google-аккаунту", "Администратор BasQar должен настроить OAuth"], steps: ["Нажмите «Подключить через Google» и выберите форму.", "Разрешите доступ к ответам формы.", "Откройте «Сопоставить поля» и назначьте вопросы для телефона, имени, email и сообщения.", "Отправьте тестовый ответ в форме.", "Нажмите «Синхронизировать» и проверьте заявку."], check: "В заявке должен быть источник Google Forms и заполненный телефон, если он был сопоставлен.", trouble: ["Нет вопросов — аккаунт не имеет доступа к форме.", "Нет заявки — проверьте сопоставление телефона и синхронизацию."] },
  google_email: { title: "Входящая почта Google", intro: "Входящие письма и поддерживаемые вложения появляются в диалогах CRM.", before: ["Google-аккаунт с доступом к Gmail", "Настроенный Google OAuth в BasQar"], steps: ["Нажмите «Подключить через Google» напротив входящей почты.", "Разрешите доступ к Gmail.", "Дождитесь первого запуска синхронизации.", "Отправьте тестовое письмо на подключённый ящик.", "Проверьте раздел «Диалоги» и журнал событий."], check: "Письмо должно появиться в диалоге с сохранённым отправителем и временем получения.", trouble: ["Ответы отправляются из Gmail; CRM импортирует входящие письма.", "Нет писем — проверьте, что OAuth выдан нужному ящику и сервер работает."] },
  meta_instagram: { title: "Instagram Direct", intro: "Входящие сообщения Instagram Direct и ответы сотрудников проходят через Meta Webhooks.", before: ["Facebook Page и профессиональный Instagram-аккаунт", "Приложение Meta с разрешениями и ролью администратора"], steps: ["Выберите Instagram Direct и заполните App ID, Page ID, Page Access Token, App Secret и версию API.", "Скопируйте Callback URL и Verify Token из результата настройки.", "В Meta Developers откройте Webhooks, выберите Instagram и поле messages.", "Сохраните webhook и нажмите «Проверить и включить» в CRM.", "Напишите аккаунту тестовое сообщение."], check: "Проверка подключения должна пройти, а сообщение — появиться в «Диалогах».", trouble: ["Webhook не подтверждается — проверьте Verify Token и публичный HTTPS.", "Ответ недоступен — Instagram должен быть профессиональным и привязанным к Page."] },
  meta_leads: { title: "Meta Lead Forms", intro: "Лиды из форм Facebook/Meta создаются как заявки CRM.", before: ["Facebook Page", "Приложение Meta с Lead Generation и правами Page"], steps: ["Выберите Meta Lead Forms и заполните данные приложения и Page.", "В Meta Developers включите Webhooks для объекта Page и поле leadgen.", "Скопируйте Callback URL и Verify Token из CRM.", "Нажмите «Проверить и включить».", "Отправьте тестовый лид из Lead Ads Testing Tool."], check: "Тестовый лид должен появиться в «Заявках» с источником Meta Lead Forms.", trouble: ["Нет лида — проверьте подписку Page и разрешение leads_retrieval.", "Лиды без телефона сохраняются для уточнения контакта."] },
  tiktok: { title: "TikTok Leads", intro: "Лиды из TikTok Instant Form передаются в CRM автоматически.", before: ["TikTok for Business", "Права администратора рекламного аккаунта и Lead Generation"], steps: ["Создайте приложение TikTok for Business.", "Укажите App ID, Advertiser ID, ID формы, Access Token и App Secret.", "Нажмите «Подключить форму».", "Нажмите «Проверить подключение» для проверки доступа к форме.", "Создайте тестовый лид и убедитесь, что он появился в CRM."], check: "Статус должен быть «Подключено», а тестовая заявка — в разделе «Заявки».", trouble: ["Ошибка доступа — токен должен иметь права на Lead Generation.", "Не тот лид — проверьте Advertiser ID и ID формы."] },
  telegram_bot: { title: "Telegram-бот компании", intro: "Клиенты пишут боту, а сотрудники отвечают из раздела «Диалоги».", before: ["Аккаунт Telegram", "Новый бот, созданный через @BotFather"], steps: ["В @BotFather выполните /newbot и скопируйте токен.", "Вставьте токен в CRM и нажмите «Подключить или обновить бота».", "Откройте бота с другого аккаунта и отправьте /start.", "Нажмите «Проверить подключение».", "Ответьте на сообщение из раздела «Диалоги»."], check: "В карточке должен быть статус «Подключено», а тестовое сообщение — в диалоге.", trouble: ["Токен уже используется другой системой — удалите старый webhook или используйте нового бота.", "Бот не отвечает — проверьте, что клиент отправил /start."] },
  whatsapp: { title: "WhatsApp через Green API", intro: "AI-менеджер получает и отправляет сообщения через экземпляр Green API.", before: ["Аккаунт Green API", "Instance ID, API Token и подключённый WhatsApp"], steps: ["Создайте или выберите instance в Green API.", "Подключите номер WhatsApp по QR-коду в Green API.", "Скопируйте Instance ID и API Token в CRM.", "Нажмите «Подключить», затем «Проверить подключение».", "Отправьте тестовое сообщение на номер и выполните синхронизацию."], check: "Статус должен быть «Активен», а в CRM появится тестовый диалог.", trouble: ["Не отвечает — проверьте состояние instance и QR-сессию.", "Не передавайте API Token в чат или публичный код."] },
  esf: { title: "ИС ЭСФ", intro: "Подписание и отправка документов в ИС ЭСФ выполняются через NCALayer на компьютере пользователя.", before: ["Установленный NCALayer и официальный модуль ИС ЭСФ", "Действующий ключ НУЦ для входа и ключ подписи", "Доступ к кабинету test3.esf.kgd.gov.kz или боевому кабинету"], steps: ["Установите и запустите NCALayer.", "Откройте страницу ИС ЭСФ и нажмите «Подключить».", "Выберите сертификат входа в NCALayer и, если потребуется, введите пароль кабинета.", "Для подписания документов выберите ключ подписи в NCALayer.", "Проверьте статус сессии и выполните тестовый POC только на тестовом контуре."], check: "В CRM должны отображаться активная сессия, БИН организации и срок действия сессии.", trouble: ["PIN не передаётся на сервер — вводите его только в NCALayer.", "Сертификат не принят — используйте сертификат входа для авторизации, а не ключ подписи."] },
  employee_telegram: { title: "Telegram сотрудника", intro: "Личные уведомления CRM отправляются сотруднику в Telegram.", before: ["Telegram на телефоне сотрудника"], steps: ["Нажмите «Подключить Telegram» в разделе уведомлений.", "Откройте deep link на бота.", "Отправьте боту /start.", "Вернитесь в CRM и дождитесь статуса подключения.", "Создайте тестовую задачу или событие."], check: "Уведомление о тестовом событии должно прийти в личный чат Telegram.", trouble: ["Это личные уведомления, а не канал заявок клиентов.", "Если уведомления не приходят, заново откройте ссылку и отправьте /start."] },
};

export function IntegrationHelp({ kind }: { kind: IntegrationHelpKind }) {
  const [open, setOpen] = useState(false);
  const content = CONTENT[kind];
  return <>
    <button type="button" className="btn secondary integration-help-button" onClick={() => setOpen(true)}>Как подключить</button>
    {open ? <div className="integration-help-backdrop" role="presentation" onClick={() => setOpen(false)}>
      <section className="panel integration-help-dialog" role="dialog" aria-modal="true" aria-labelledby={`integration-help-${kind}`} onClick={(event) => event.stopPropagation()}>
        <div className="row"><h3 id={`integration-help-${kind}`}>{content.title}: как подключить</h3><button type="button" className="btn secondary" onClick={() => setOpen(false)}>Закрыть</button></div>
        <p>{content.intro}</p><h4>Перед началом</h4><ul>{content.before.map(item => <li key={item}>{item}</li>)}</ul><h4>Порядок подключения</h4><ol>{content.steps.map(item => <li key={item}>{item}</li>)}</ol><h4>Как проверить</h4><p>{content.check}</p><h4>Если не работает</h4><ul>{content.trouble.map(item => <li key={item}>{item}</li>)}</ul>
      </section>
    </div> : null}
  </>;
}
