import { FEATURES, LIMITS, type CatalogStatus, type Feature, type LimitKey } from "./entitlements.ts";

export type CatalogKind = "plan" | "bundle" | "addon" | "legacy";
export type CatalogProduct = "CRM" | "AI" | "CONTROL" | "BUNDLE" | "ADDON";
export type CatalogChargeType = "RECURRING" | "ONE_TIME";

export type CatalogItem = {
  code: string;
  name: string;
  product: CatalogProduct;
  kind: CatalogKind;
  monthlyPriceMinor: number;
  yearlyPriceMinor: number;
  public: boolean;
  active: boolean;
  catalogStatus: CatalogStatus;
  chargeType: CatalogChargeType;
  recommended?: boolean;
  sortOrder: number;
  description: string;
  features: Partial<Record<Feature, boolean>>;
  limits: Partial<Record<LimitKey, number>> & { members?: number; whatsappActive?: number };
  included?: Array<{ code: string; qty: number }>;
  limitDelta?: boolean;
};

const F = FEATURES;
const L = LIMITS;

const CRM_BASE: Partial<Record<Feature, boolean>> = {
  [F.CRM_CORE]: true,
  [F.CLIENTS]: true,
  [F.COMPANIES]: true,
  [F.LEADS]: true,
  [F.DEALS]: true,
  [F.TASKS]: true,
  [F.TEAM]: true,
  [F.AUTOMATION]: true,
};

const CRM_LITE: Partial<Record<Feature, boolean>> = {
  [F.CRM_LITE]: true,
  [F.CLIENTS]: true,
  [F.LEADS]: true,
  [F.DEALS]: true,
  [F.TASKS]: true,
  [F.TEAM]: true,
  [F.AUTOMATION]: true,
};

const BUSINESS_PLUS: Partial<Record<Feature, boolean>> = {
  ...CRM_BASE,
  [F.MULTIPLE_PIPELINES]: true,
  [F.WORKFLOWS]: true,
  [F.ADVANCED_ANALYTICS]: true,
  [F.DOCUMENTS]: true,
  [F.AVR_ESF]: true,
  [F.ESF]: true,
  [F.MASS_MESSAGING]: true,
  [F.CHANNELS]: true,
  [F.ADVANCED_ROLES]: true,
};

const PRO_PLUS: Partial<Record<Feature, boolean>> = {
  ...BUSINESS_PLUS,
  [F.API]: true,
  [F.API_ACCESS]: true,
  [F.MULTI_DEPARTMENT]: true,
};

const AI_FEATURES: Partial<Record<Feature, boolean>> = {
  [F.AI_MANAGER]: true,
  [F.WHATSAPP]: true,
  [F.MESSAGING]: true,
  [F.CHANNELS]: true,
};

function yearly(monthly: number) {
  return monthly * 10;
}

export const PRICING_CATALOG: CatalogItem[] = [
  {
    code: "CRM_START",
    name: "CRM Start",
    product: "CRM",
    kind: "plan",
    monthlyPriceMinor: 14900,
    yearlyPriceMinor: yearly(14900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 10,
    description: "Полноценная CRM для небольшого бизнеса: клиенты, заявки, сделки, задачи, одна воронка.",
    features: CRM_BASE,
    limits: { [L.USERS]: 3, members: 3, [L.PIPELINES]: 1, [L.DEPARTMENTS]: 1, [L.WHATSAPP_CONNECTIONS]: 0, whatsappActive: 0, [L.AI_USAGE]: 0, [L.STORAGE_GB]: 5 },
  },
  {
    code: "CRM_BUSINESS",
    name: "CRM Business",
    product: "CRM",
    kind: "plan",
    monthlyPriceMinor: 29900,
    yearlyPriceMinor: yearly(29900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 20,
    description: "Основной CRM-тариф: несколько воронок, документы, workflow, аналитика, до 10 пользователей.",
    features: BUSINESS_PLUS,
    limits: { [L.USERS]: 10, members: 10, [L.PIPELINES]: 5, [L.DEPARTMENTS]: 1, [L.WHATSAPP_CONNECTIONS]: 0, whatsappActive: 0, [L.AI_USAGE]: 0, [L.STORAGE_GB]: 10 },
  },
  {
    code: "CRM_PRO",
    name: "CRM Pro",
    product: "CRM",
    kind: "plan",
    monthlyPriceMinor: 49900,
    yearlyPriceMinor: yearly(49900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 30,
    description: "Корпоративная CRM: отделы, API, расширенные роли, до 25 пользователей.",
    features: PRO_PLUS,
    limits: { [L.USERS]: 25, members: 25, [L.PIPELINES]: 20, [L.DEPARTMENTS]: 5, [L.WHATSAPP_CONNECTIONS]: 0, whatsappActive: 0, [L.AI_USAGE]: 0, [L.STORAGE_GB]: 25 },
  },
  {
    code: "CRM_ENTERPRISE",
    name: "Enterprise",
    product: "CRM",
    kind: "plan",
    monthlyPriceMinor: 0,
    yearlyPriceMinor: 0,
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 40,
    description: "Индивидуальные лимиты, SLA и цена. Запрос уходит администратору BasQar.",
    features: { ...PRO_PLUS, [F.PRIORITY_SUPPORT]: true },
    limits: { [L.USERS]: 50, members: 50, [L.PIPELINES]: 50, [L.DEPARTMENTS]: 20, [L.WHATSAPP_CONNECTIONS]: 0, [L.AI_USAGE]: 0, [L.STORAGE_GB]: 100 },
  },
  {
    code: "AI_SALES",
    name: "BasQar AI Sales",
    product: "AI",
    kind: "plan",
    monthlyPriceMinor: 29900,
    yearlyPriceMinor: yearly(29900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 50,
    description: "AI Manager без полной CRM: WhatsApp-продажи и CRM Lite на тех же клиентах, заявках и сделках.",
    features: { ...CRM_LITE, ...AI_FEATURES },
    limits: { [L.USERS]: 3, members: 3, [L.PIPELINES]: 1, [L.DEPARTMENTS]: 1, [L.WHATSAPP_CONNECTIONS]: 1, whatsappActive: 1, [L.AI_USAGE]: 3000, [L.STORAGE_GB]: 5 },
  },
  {
    code: "CONTROL_STANDALONE",
    name: "BasQar Control",
    product: "CONTROL",
    kind: "plan",
    monthlyPriceMinor: 19900,
    yearlyPriceMinor: yearly(19900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 60,
    description: "Управление CRM командами из WhatsApp и других каналов плюс CRM Lite.",
    features: { ...CRM_LITE, [F.AI_CONTROL]: true },
    limits: { [L.USERS]: 3, members: 3, [L.PIPELINES]: 1, [L.DEPARTMENTS]: 1, [L.WHATSAPP_CONNECTIONS]: 0, [L.AI_USAGE]: 0, [L.STORAGE_GB]: 5 },
  },
  {
    code: "BUNDLE_CRM_AI",
    name: "CRM + AI",
    product: "BUNDLE",
    kind: "bundle",
    monthlyPriceMinor: 49900,
    yearlyPriceMinor: yearly(49900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    recommended: true,
    sortOrder: 5,
    description: "CRM Business и AI Manager Business вместе. Отдельно это 59 800 ₸.",
    features: { ...BUSINESS_PLUS, ...AI_FEATURES },
    limits: { [L.USERS]: 10, members: 10, [L.PIPELINES]: 5, [L.DEPARTMENTS]: 1, [L.WHATSAPP_CONNECTIONS]: 1, whatsappActive: 1, [L.AI_USAGE]: 3000, [L.STORAGE_GB]: 10 },
    included: [
      { code: "CRM_BUSINESS", qty: 1 },
      { code: "ADDON_AI_BUSINESS", qty: 1 },
    ],
  },
  {
    code: "BUNDLE_FULL",
    name: "BasQar Full",
    product: "BUNDLE",
    kind: "bundle",
    monthlyPriceMinor: 69900,
    yearlyPriceMinor: yearly(69900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 8,
    description: "CRM Business, AI Manager, Control, 2 WhatsApp, документы и приоритетная поддержка.",
    features: { ...BUSINESS_PLUS, ...AI_FEATURES, [F.AI_CONTROL]: true, [F.API]: true, [F.API_ACCESS]: true, [F.PRIORITY_SUPPORT]: true },
    limits: { [L.USERS]: 10, members: 10, [L.PIPELINES]: 5, [L.DEPARTMENTS]: 1, [L.WHATSAPP_CONNECTIONS]: 2, whatsappActive: 2, [L.AI_USAGE]: 5000, [L.STORAGE_GB]: 20 },
    included: [
      { code: "CRM_BUSINESS", qty: 1 },
      { code: "ADDON_AI_BUSINESS", qty: 1 },
      { code: "ADDON_CONTROL", qty: 1 },
    ],
  },
  {
    code: "ADDON_AI_START",
    name: "AI Manager Start",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 19900,
    yearlyPriceMinor: yearly(19900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 110,
    description: "Полноценный AI-продажи: консультации, возражения, заявки и сделки. 1 WhatsApp.",
    features: AI_FEATURES,
    limits: { [L.WHATSAPP_CONNECTIONS]: 1, whatsappActive: 1, [L.AI_USAGE]: 1000 },
    limitDelta: true,
  },
  {
    code: "ADDON_AI_BUSINESS",
    name: "AI Manager Business",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 29900,
    yearlyPriceMinor: yearly(29900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 120,
    description: "Основной AI-пакет: тот же интеллект, больше объёма. 1 WhatsApp.",
    features: AI_FEATURES,
    limits: { [L.WHATSAPP_CONNECTIONS]: 1, whatsappActive: 1, [L.AI_USAGE]: 3000 },
    limitDelta: true,
  },
  {
    code: "ADDON_AI_PRO",
    name: "AI Manager Pro",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 49900,
    yearlyPriceMinor: yearly(49900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 130,
    description: "Масштаб: до 2 WhatsApp и высокий лимит AI.",
    features: AI_FEATURES,
    limits: { [L.WHATSAPP_CONNECTIONS]: 2, whatsappActive: 2, [L.AI_USAGE]: 8000 },
    limitDelta: true,
  },
  {
    code: "ADDON_CONTROL",
    name: "BasQar Control",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 9900,
    yearlyPriceMinor: yearly(9900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 140,
    description: "Команды к CRM из WhatsApp: статистика, задачи, сделки.",
    features: { [F.AI_CONTROL]: true },
    limits: {},
    limitDelta: true,
  },
  {
    code: "ADDON_USER",
    name: "Дополнительный пользователь",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 3900,
    yearlyPriceMinor: yearly(3900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 150,
    description: "Ещё один пользователь сверх лимита тарифа.",
    features: {},
    limits: { [L.USERS]: 1, members: 1 },
    limitDelta: true,
  },
  {
    code: "ADDON_WHATSAPP",
    name: "Дополнительный WhatsApp",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 9900,
    yearlyPriceMinor: yearly(9900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 160,
    description: "Ещё один номер WhatsApp.",
    features: { [F.WHATSAPP]: true, [F.MESSAGING]: true },
    limits: { [L.WHATSAPP_CONNECTIONS]: 1, whatsappActive: 1 },
    limitDelta: true,
  },
  {
    code: "ADDON_AI_PACK",
    name: "Дополнительный пакет AI",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 9900,
    yearlyPriceMinor: yearly(9900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 170,
    description: "+1000 AI-взаимодействий в период подписки.",
    features: { [F.AI_MANAGER]: true },
    limits: { [L.AI_USAGE]: 1000 },
    limitDelta: true,
  },
  {
    code: "ADDON_STORAGE_10GB",
    name: "Хранилище +10 ГБ",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 2900,
    yearlyPriceMinor: yearly(2900),
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "RECURRING",
    sortOrder: 180,
    description: "Дополнительные 10 ГБ файлов.",
    features: {},
    limits: { [L.STORAGE_GB]: 10 },
    limitDelta: true,
  },
  {
    code: "ADDON_TELEGRAM",
    name: "Telegram",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 4900,
    yearlyPriceMinor: yearly(4900),
    public: true,
    active: true,
    catalogStatus: "COMING_SOON",
    chargeType: "RECURRING",
    sortOrder: 210,
    description: "Клиентский канал Telegram — в подготовке.",
    features: { [F.TELEGRAM]: true },
    limits: {},
    limitDelta: true,
  },
  {
    code: "ADDON_INSTAGRAM",
    name: "Instagram",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 6900,
    yearlyPriceMinor: yearly(6900),
    public: true,
    active: true,
    catalogStatus: "COMING_SOON",
    chargeType: "RECURRING",
    sortOrder: 220,
    description: "Клиентский канал Instagram — в подготовке.",
    features: { [F.INSTAGRAM]: true },
    limits: {},
    limitDelta: true,
  },
  {
    code: "ADDON_DEPARTMENT",
    name: "Дополнительный отдел",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 7900,
    yearlyPriceMinor: yearly(7900),
    public: true,
    active: true,
    catalogStatus: "COMING_SOON",
    chargeType: "RECURRING",
    sortOrder: 230,
    description: "Отделы как оргструктура — в подготовке.",
    features: { [F.MULTI_DEPARTMENT]: true },
    limits: { [L.DEPARTMENTS]: 1 },
    limitDelta: true,
  },
  {
    code: "ADDON_TELEPHONY",
    name: "Телефония",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 7900,
    yearlyPriceMinor: yearly(7900),
    public: true,
    active: true,
    catalogStatus: "COMING_SOON",
    chargeType: "RECURRING",
    sortOrder: 240,
    description: "Подключение телефонии. Стоимость оператора отдельно.",
    features: { [F.TELEPHONY]: true },
    limits: {},
    limitDelta: true,
  },
  {
    code: "ADDON_INTEGRATION",
    name: "Индивидуальная интеграция",
    product: "ADDON",
    kind: "addon",
    monthlyPriceMinor: 50000,
    yearlyPriceMinor: 50000,
    public: true,
    active: true,
    catalogStatus: "AVAILABLE",
    chargeType: "ONE_TIME",
    sortOrder: 250,
    description: "Разовая индивидуальная интеграция от 50 000 ₸.",
    features: { [F.CHANNELS]: true },
    limits: {},
    limitDelta: true,
  },
];

export const CATALOG_BY_CODE = Object.fromEntries(PRICING_CATALOG.map((item) => [item.code, item])) as Record<
  string,
  CatalogItem
>;

export const PUBLIC_OFFERS = [
  { code: "CRM_START", group: "CRM", fromCode: "CRM_START", title: "CRM", subtitle: "от 14 900 ₸ / месяц" },
  { code: "AI_SALES", group: "AI", fromCode: "AI_SALES", title: "AI Manager", subtitle: "от 29 900 ₸ / месяц" },
  { code: "BUNDLE_CRM_AI", group: "BUNDLE", fromCode: "BUNDLE_CRM_AI", title: "CRM + AI", subtitle: "49 900 ₸ / месяц", recommended: true },
  { code: "BUNDLE_FULL", group: "BUNDLE", fromCode: "BUNDLE_FULL", title: "BasQar Full", subtitle: "69 900 ₸ / месяц" },
  { code: "CRM_ENTERPRISE", group: "CRM", fromCode: "CRM_ENTERPRISE", title: "Enterprise", subtitle: "Индивидуально" },
] as const;
