import type { PrismaClient } from '@creolab/db';
import { getDocumentSignMeta, type DocumentSignType } from '@creolab/contracts';
import { ApiError } from '../errors.ts';

const loaders = {
  AVR: async (db: PrismaClient, token: string) => (await import('./avrSigningService.ts')).getPublicAvrSignMetaDocument(db, token),
  CONTRACT: async (db: PrismaClient, token: string) => (await import('./contractSigningService.ts')).getPublicContractSignMetaDocument(db, token),
};
export type PublicSignRouteType = keyof typeof loaders;
export async function loadPublicSignMeta(db: PrismaClient, type: PublicSignRouteType, token: string) {
  try {
    // Bound invalid input before hashing/querying; links generated by both signing services are hex tokens.
    if (!/^[a-zA-Z0-9_-]{16,256}$/.test(token)) return getDocumentSignMeta(type);
    return getDocumentSignMeta(type, await loaders[type](db, token));
  } catch (error) {
    if (error instanceof ApiError && [404, 409, 410].includes(error.status)) return getDocumentSignMeta(type);
    throw error;
  }
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
}
/** No URL from the request is copied here: it contains the bearer token. */
export function renderPublicSignHtml(template: string, meta: ReturnType<typeof getDocumentSignMeta>, appBaseUrl: string) {
  const origin = new URL(appBaseUrl).origin;
  const image = new URL(meta.preview.image, origin).href;
  const tags = [
    `<title>${escapeHtml(meta.pageTitle)}</title>`,
    ['name', 'description', meta.description],
    ['name', 'robots', 'noindex, nofollow, noarchive'],
    ['name', 'referrer', 'no-referrer'],
    ['property', 'og:title', meta.pageTitle],
    ['property', 'og:description', meta.description],
    ['property', 'og:image', image],
    ['property', 'og:image:type', 'image/png'],
    ['property', 'og:image:width', String(meta.preview.width)],
    ['property', 'og:image:height', String(meta.preview.height)],
    ['property', 'og:image:alt', meta.preview.imageAlt],
    ['property', 'og:url', `${origin}/`],
    ['property', 'og:type', meta.preview.type],
    ['property', 'og:site_name', 'BasQar'],
    ['property', 'og:locale', 'ru_RU'],
    ['name', 'twitter:card', 'summary_large_image'],
    ['name', 'twitter:title', meta.pageTitle],
    ['name', 'twitter:description', meta.description],
    ['name', 'twitter:image', image],
    ['name', 'twitter:image:alt', meta.preview.imageAlt],
  ].map(tag => typeof tag === 'string' ? tag : `<meta ${tag[0]}="${tag[1]}" content="${escapeHtml(tag[2])}" />`).join('\n    ');
  return template
    .replace(/<title\b[^>]*>[\s\S]*?<\/title>/gi, '')
    .replace(/<meta\b[^>]*(?:name|property)\s*=\s*["'](?:description|robots|referrer|og:[^"']*|twitter:[^"']*)["'][^>]*>/gi, '')
    .replace('</head>', `${tags}\n  </head>`);
}
