import { useEffect, useMemo, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { AI_MANAGER_ROLES, compileAiManagerDraft, type AiManagerDraft, type AiManagerRole, type AiSetupState, type AiSetupIssue } from "@creolab/contracts";
import { api } from "../lib/api";
import { useLocale, useSession } from "../lib/session";
import { InlineFeedback } from "../components/InlineFeedback";
import { AiGoalPicker, AiSetupQualityChecks } from "../components/AiManagerSetupChecks";
import { notifySaved } from "../components/SaveNotice";
import "../ai-manager-setup.css";

type Field = { path: string; label: string; hint?: string; required?: boolean; max?: number; short?: boolean };
type ChatMessage = { role: "user" | "assistant"; content: string };
const stepFor = (field: string) => field.startsWith("company") ? 1 : field.startsWith("offerings") ? 2 : field.startsWith("conversation") ? 3 : field.startsWith("terms") ? 4 : field.startsWith("faq") || field.startsWith("knowledge") ? 5 : 6;
function getField(draft: AiManagerDraft, path: string): string {
  return path.split(".").reduce<any>((value, part) => value?.[part], draft) ?? "";
}
function Question({ field, value, onChange }: { field: Field; value: string; onChange: (value: string) => void }) {
  const id = `ai-setup-${field.path}`;
  return <label className="ai-setup-field" htmlFor={id}><span>{field.label}{field.required && <span className="ai-setup-required"> *</span>}</span>
    {field.short ? <input id={id} value={value} maxLength={field.max || 4000} onChange={event => onChange(event.target.value)} aria-required={field.required} aria-describedby={field.hint ? `${id}-hint` : undefined} /> : <textarea id={id} rows={3} value={value} maxLength={field.max || 4000} onChange={event => onChange(event.target.value)} aria-required={field.required} aria-describedby={field.hint ? `${id}-hint` : undefined} />}
    {field.hint && <span className="ai-setup-help" id={`${id}-hint`}>{field.hint}</span>}</label>;
}

export function AiManagerSetupPage() {
  const locale = useLocale(); const { me } = useSession();
  const text = (ru: string, kk: string, en: string) => locale === "kk" ? kk : locale === "en" ? en : ru;
  const [state, setState] = useState<AiSetupState | null>(null), [draft, setDraft] = useState<AiManagerDraft | null>(null);
  const [step, setStep] = useState(0), [error, setError] = useState(""), [busy, setBusy] = useState(false), [testing, setTesting] = useState(false);
  const [chat, setChat] = useState<ChatMessage[]>([]), [message, setMessage] = useState(""), [handedOff, setHandedOff] = useState(false), [approved, setApproved] = useState(false);
  const [confirm, setConfirm] = useState<{ action: "restore" | "reload"; versionId?: string } | null>(null);
  const sectionRef = useRef<HTMLHeadingElement>(null), chatRef = useRef<HTMLDivElement>(null), confirmRef = useRef<HTMLDivElement>(null);
  const dirty = Boolean(state && draft && JSON.stringify(state.draft) !== JSON.stringify(draft));
  const compiled = useMemo(() => draft ? compileAiManagerDraft(draft) : null, [draft]);
  const blockers = compiled?.issues.filter(issue => issue.level === "error") || [];
  const allowed = Boolean(me?.billing?.entitlements?.AI_MANAGER);
  const updateState = (next: AiSetupState) => { setState(next); setDraft(next.draft); setApproved(false); setChat([]); setHandedOff(false); };
  async function load() { setError(""); try { updateState(await api.aiManagerSetup()); } catch (err) { setError(err instanceof Error ? err.message : text("Не удалось загрузить настройки", "Баптаулар жүктелмеді", "Could not load settings")); } }
  useEffect(() => { void load(); }, []);
  useEffect(() => {
    if (!dirty) return;
    const unload = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; };
    const leave = (event: MouseEvent) => {
      const link = (event.target as Element).closest?.("a[href]");
      if (link && !link.getAttribute("target") && !window.confirm(text("Есть несохранённые ответы. Покинуть мастер?", "Сақталмаған жауаптар бар. Шеберден шығу керек пе?", "You have unsaved answers. Leave the wizard?"))) { event.preventDefault(); event.stopPropagation(); }
    };
    window.addEventListener("beforeunload", unload); document.addEventListener("click", leave, true);
    return () => { window.removeEventListener("beforeunload", unload); document.removeEventListener("click", leave, true); };
  }, [dirty, locale]);
  useEffect(() => { if (confirm) { confirmRef.current?.scrollIntoView({ block: "center", behavior: "instant" }); confirmRef.current?.focus({ preventScroll: true }); } }, [confirm]);
  useEffect(() => { chatRef.current?.scrollTo({ top: chatRef.current.scrollHeight, behavior: "instant" }); }, [chat, testing]);
  function edit(path: string, value: unknown) {
    setDraft(current => { if (!current) return current; const next = structuredClone(current); const parts = path.split("."); let parent: any = next; for (const part of parts.slice(0, -1)) parent = parent[part]; parent[parts.at(-1)!] = value; return next; });
    setApproved(false); setChat([]); setHandedOff(false);
  }
  function go(next: number) { setStep(next); setConfirm(null); requestAnimationFrame(() => { sectionRef.current?.scrollIntoView({ block: "start", behavior: "instant" }); sectionRef.current?.focus({ preventScroll: true }); }); }
  async function save() { if (!state || !draft) return; setBusy(true); setError(""); try { updateState(await api.saveAiManagerSetup({ revision: state.revision, draft })); notifySaved(text("Черновик сохранён", "Жоба сақталды", "Draft saved")); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  async function publish() {
    if (!state || dirty || !approved || blockers.length || !state.quality?.ready) return; setBusy(true); setError("");
    try { updateState(await api.publishAiManagerSetup({ revision: state.revision })); notifySaved(text("Инструкции и знания опубликованы", "Нұсқаулық пен білім жарияланды", "Instructions and knowledge published")); }
    catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }
  async function restore() {
    if (!state || !confirm) return; setBusy(true); setError("");
    try { updateState(confirm.action === "reload" ? await api.reloadAiManagerSetup({ revision: state.revision }) : await api.restoreAiManagerSetup({ revision: state.revision, versionId: confirm.versionId! })); setConfirm(null); notifySaved(text("Настройки обновлены", "Баптаулар жаңартылды", "Settings updated")); }
    catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }
  async function testReply() {
    if (!state || !message.trim() || dirty || blockers.length || testing || handedOff) return;
    const history: ChatMessage[] = [...chat, { role: "user", content: message.trim() }];
    setTesting(true); setError("");
    try { const result = await api.previewAiManagerSetup({ revision: state.revision, messages: history }); setChat([...history, { role: "assistant", content: result.handoff ? text("ИИ передал бы вопрос сотруднику: нужны сведения или действия человека.", "ЖИ сұрақты қызметкерге берер еді: адам көмегі қажет.", "AI would hand this question to a staff member: information or action is needed.") : result.reply }]); setMessage(""); setHandedOff(result.handoff); }
    catch (err) { setError((err as Error).message); } finally { setTesting(false); }
  }
  const roles: Record<AiManagerRole, [string, string]> = {
    consultation: [text("Консультация", "Кеңес беру", "Consultation"), text("Объясняет услуги, цены и условия", "Қызметтерді, бағаны және шарттарды түсіндіреді", "Explains services, prices and terms")],
    sales: [text("Продажи", "Сату", "Sales"), text("Подбирает предложение и ведёт к следующему шагу", "Ұсыныс таңдап, келесі қадамға жетелейді", "Recommends an offer and guides to the next step")],
    qualification: [text("Квалификация заявок", "Өтінімдерді нақтылау", "Lead qualification"), text("Собирает задачу, требования, бюджет и сроки", "Міндетті, талапты, бюджетті және мерзімді жинайды", "Collects needs, requirements, budget and timing")],
    booking: [text("Запись на услугу", "Қызметке жазылу", "Booking requests"), text("Собирает пожелания для записи, передаёт сотруднику", "Жазылу тілектерін жинап, қызметкерге береді", "Collects appointment preferences for a staff member")],
    support: [text("Поддержка", "Қолдау", "Support"), text("Помогает по инструкциям, передаёт сложные вопросы", "Нұсқаулық бойынша көмектесіп, күрделі сұрақтарды береді", "Helps with approved instructions and escalates complex issues")],
  };
  const steps = [text("Функции ИИ", "ЖИ міндеттері", "AI functions"), text("Компания", "Компания", "Company"), text("Услуги и товары", "Қызмет пен тауар", "Services and products"), text("Сценарий разговора", "Әңгіме сценарийі", "Conversation flow"), text("Условия", "Шарттар", "Terms"), text("База знаний", "Білім базасы", "Knowledge"), text("Общение и помощь", "Қарым-қатынас және көмек", "Style and handoff"), text("Проверка и запуск", "Тексеру және іске қосу", "Review and publish")];
  const descriptions = [text("Выберите основную задачу. Дополнительные функции можно сочетать с ней.", "Негізгі міндетті таңдаңыз. Қосымша міндеттерді біріктіруге болады.", "Choose the primary task. Add supporting functions if needed."), text("Заполняйте только достоверные сведения. ИИ будет использовать их в ответах.", "Тек нақты ақпаратты толтырыңыз. ЖИ оны жауаптарда қолданады.", "Provide verified facts that AI can use in replies."), text("Добавьте отдельную карточку для каждого предложения. Если цена индивидуальная, так и напишите.", "Әр ұсынысқа жеке карточка қосыңыз. Баға жеке есептелсе, соны жазыңыз.", "Add a card for each offer. Say explicitly when pricing is custom."), text("Опишите результат разговора и важные вопросы. ИИ не станет повторно спрашивать уже известное.", "Әңгіме нәтижесін және маңызды сұрақтарды сипаттаңыз. ЖИ белгілі ақпаратты қайта сұрамайды.", "Define the outcome and key questions. AI should not ask for details already provided."), text("Пустое поле означает, что условие неизвестно. ИИ уточнит его у сотрудника.", "Бос өріс — шарт белгісіз. ЖИ оны қызметкерден нақтылайды.", "A blank field means the term is unknown. AI will ask staff rather than guess."), text("Готовые ответы, инструкции и дополнительные материалы. Можно вставить текст из ваших документов.", "Дайын жауаптар, нұсқаулар және материалдар. Құжат мәтінін қоюға болады.", "Approved answers, instructions and reference material. Paste text from your documents."), text("Выберите тон общения и объясните, когда нужна помощь человека.", "Қарым-қатынас стилін таңдап, адам көмегі қашан керек екенін түсіндіріңіз.", "Choose the tone and define when a person should help."), text("Проверьте сведения и попробуйте ИИ в тестовом чате. Только публикация меняет действующие инструкции.", "Ақпаратты тексеріп, ЖИ-ді сынақ чатта көріңіз. Тек жариялау қолданыстағы нұсқаулықты өзгертеді.", "Review the facts and try a test conversation. Only publishing changes the live instructions.")];
  function fields(items: Field[]) { return <div className="ai-setup-fields">{items.map(field => <Question key={field.path} field={field} value={getField(draft!, field.path)} onChange={value => edit(field.path, value)} />)}</div>; }
  function issueLabel(issue: AiSetupIssue) { return locale === "ru" ? issue.message : text(issue.message, `${steps[stepFor(issue.field)]}: ${issue.level === "error" ? "міндетті өрістерді және қайталанған мәтінді тексеріңіз" : "мәліметтерді толықтырыңыз"}`, `${steps[stepFor(issue.field)]}: ${issue.level === "error" ? "check required fields and duplicate entries" : "add missing details"}`); }
  const remove = (key: "offerings" | "faq" | "knowledge", index: number) => edit(key, draft![key].filter((_, i) => i !== index));
  const removeButton = (key: "offerings" | "faq" | "knowledge", index: number) => <button type="button" className="ai-setup-remove" onClick={() => remove(key, index)}>{text("Удалить", "Жою", "Remove")}</button>;
  if (!state || !draft || !compiled) return <section className="panel">{error ? <><InlineFeedback className="error">{error}</InlineFeedback><button className="btn" onClick={() => void load()}>{text("Повторить", "Қайталау", "Retry")}</button></> : <p>{text("Загружаем мастер…", "Шебер жүктелуде…", "Loading setup…")}</p>}</section>;
  const selectedRoles = [draft.primaryRole, ...draft.additionalRoles];
  const canTest = allowed && !dirty && !blockers.length && !busy && chat.length < 18 && !handedOff;
  return <section className="ai-setup">
    <header className="ai-setup-heading"><div><Link to="/settings/ai-automation" className="page-kicker">← {text("Управление ИИ", "ЖИ басқару", "AI controls")}</Link><h2>{text("Обучите ИИ вашему бизнесу", "ЖИ-ге бизнесіңізді таныстырыңыз", "Teach AI about your business")}</h2><p>{text("Ответьте на вопросы — BasQar соберёт инструкции и базу знаний. Можно заполнить постепенно.", "Сұрақтарға жауап беріңіз — BasQar нұсқаулық пен білім базасын құрастырады. Біртіндеп толтыруға болады.", "Answer the questions and BasQar will assemble instructions and knowledge. Work at your own pace.")}</p></div><span className="badge">{dirty || state.hasDraftChanges ? text("Черновик", "Жоба", "Draft") : text("Опубликовано", "Жарияланды", "Published")}</span></header>
    {error && <InlineFeedback className="error">{error}</InlineFeedback>}
    <div className="ai-setup-intro"><div><b>{text("Общие правила уже включены", "Ортақ ережелер қосылған", "Core rules are included")}</b>
      <p>{text("Отвечать только по задачам компании. Брать сведения из ваших инструкций и базы знаний. На посторонние вопросы вежливо возвращать разговор к услугам компании.", "Тек компанияның міндеттері бойынша жауап беру. Ақпаратты сіздің нұсқаулықтарыңыз бен білім базасынан алу. Тақырыпқа қатысы жоқ сұрақтарда әңгімені компания қызметтеріне сыпайы қайтару.", "Answer only within the company's scope. Use facts from your instructions and knowledge base. Politely redirect unrelated questions to the company's services.")}</p>
      <p>{text("Если сведений нет, они неоднозначны или противоречат друг другу — не выдумывать ответ. Уточнять вопрос или передавать его сотруднику.", "Ақпарат болмаса, түсініксіз немесе бір-біріне қайшы болса, жауапты ойдан шығармау. Сұрақты нақтылау немесе қызметкерге беру.", "If information is missing, ambiguous or conflicting, never guess. Clarify the question or hand it over to a staff member.")}</p>
      <p>{text("Поздороваться один раз, учитывать историю и отвечать на русском или казахском. Эти правила действуют для всех функций.", "Бір рет амандасу, әңгіме тарихын ескеру және орысша немесе қазақша жауап беру. Бұл ережелер барлық міндетке ортақ.", "Greet once, remember the conversation and reply in Russian or Kazakh. These rules apply to every function.")}</p>
    </div></div>
    {state.liveChanged && <div className="ai-setup-guidance"><b>{text("Действующая версия изменена администратором", "Қолданыстағы нұсқаны әкімші өзгертті", "The live version was changed by an administrator")}</b><p>{text("Чтобы не перезаписать новые сведения, загрузите их в мастер. Текущие ответы черновика будут заменены.", "Жаңа деректерді өшірмеу үшін оларды шеберге жүктеңіз. Қазіргі жоба жауаптары ауыстырылады.", "Load the updated live content into the wizard before publishing. This replaces the current draft answers.")}</p><button className="btn secondary" disabled={busy || testing} onClick={() => setConfirm({ action: "reload" })}>{text("Загрузить действующую версию", "Қолданыстағы нұсқаны жүктеу", "Load live version")}</button></div>}
    {confirm && <div ref={confirmRef} tabIndex={-1} role="alertdialog" aria-label={text("Подтверждение изменения", "Өзгерісті растау", "Confirm change")} className="ai-setup-guidance"><b>{confirm.action === "reload" ? text("Заменить черновик действующей версией?", "Жобаны қолданыстағы нұсқамен ауыстыру керек пе?", "Replace draft with the live version?") : text("Восстановить эту версию для ответов клиентам?", "Клиент жауаптары үшін осы нұсқаны қалпына келтіру керек пе?", "Restore this version for customer replies?")}</b><p>{text("Текущий черновик будет заменён. История опубликованных версий сохранится.", "Қазіргі жоба ауыстырылады. Жарияланған нұсқалар тарихы сақталады.", "The current draft will be replaced. Published version history is retained.")}</p><div className="actions"><button className="btn" disabled={busy || testing} onClick={() => void restore()}>{text("Подтвердить", "Растау", "Confirm")}</button><button className="btn secondary" disabled={busy} onClick={() => setConfirm(null)}>{text("Отмена", "Бас тарту", "Cancel")}</button></div></div>}
    <div className="ai-setup-layout"><nav className="ai-setup-nav" aria-label={text("Шаги настройки", "Баптау қадамдары", "Setup steps")}>{steps.map((label, i) => <button type="button" key={i} aria-current={step === i ? "step" : undefined} onClick={() => go(i)}><span className="ai-setup-step-number">{i + 1}</span>{label}</button>)}<div className="ai-setup-nav-meta">{text("Черновик не влияет на ответы клиентам до публикации.", "Жоба жарияланғанша клиент жауаптарына әсер етпейді.", "Drafts do not affect customer replies until published.")}</div></nav>
    <div className="ai-setup-main"><fieldset className="ai-setup-editor" disabled={busy || testing}>
      <div className="ai-setup-section-head"><p className="ai-setup-eyebrow">{step + 1} / {steps.length}</p><h3 ref={sectionRef} tabIndex={-1}>{steps[step]}</h3><p>{descriptions[step]}</p></div>
      {step === 0 && <><div className="ai-setup-role-grid">{AI_MANAGER_ROLES.map(role => <label key={role} className={`ai-setup-role ${draft.primaryRole === role ? "is-selected" : ""}`}><input type="radio" name="primaryRole" checked={draft.primaryRole === role} onChange={() => { edit("primaryRole", role); edit("additionalRoles", draft.additionalRoles.filter(value => value !== role)); }} /><span><b>{roles[role][0]}</b><small>{roles[role][1]}</small></span></label>)}</div><div className="ai-setup-subsection"><h4>{text("Дополнительные функции", "Қосымша міндеттер", "Additional functions")}</h4><p>{text("Например: продавать, а при сложном вопросе — собрать заявку для сотрудника.", "Мысалы: сату, күрделі сұрақ болса — қызметкерге өтінім жинау.", "For example: sell, then qualify complex requests for staff.")}</p><div className="ai-setup-checks">{AI_MANAGER_ROLES.filter(role => role !== draft.primaryRole).map(role => <label className="ai-setup-check" key={role}><input type="checkbox" checked={draft.additionalRoles.includes(role)} onChange={event => edit("additionalRoles", event.target.checked ? [...draft.additionalRoles, role] : draft.additionalRoles.filter(value => value !== role))} />{roles[role][0]}</label>)}</div></div></>}
      {step === 1 && fields([
        { path: "company.name", label: text("Как называется компания?", "Компания атауы қандай?", "What is the company name?"), short: true, max: 300, required: true },
        { path: "company.description", label: text("Чем вы занимаетесь?", "Немен айналысасыз?", "What does your business do?"), required: true, hint: text("Например: разрабатываем сайты и презентации для бизнеса.", "Мысалы: бизнеске сайттар мен презентациялар жасаймыз.", "For example: we create websites and presentations for businesses.") },
        { path: "company.audience", label: text("Кто ваши клиенты?", "Клиенттеріңіз кімдер?", "Who are your customers?"), max: 2000 },
        { path: "company.geography", label: text("Где работаете и по каким адресам?", "Қай жерде жұмыс істейсіз?", "Where do you operate?"), max: 1500 },
        { path: "company.contacts", label: text("Как с вами связаться?", "Сізбен қалай байланысуға болады?", "How can customers contact you?"), max: 2000, hint: text("Публичный телефон, email, сайт. Без паролей и ключей доступа.", "Жария телефон, email, сайт. Құпиясөз бен кілтсіз.", "Public phone, email and website. No passwords or API keys.") },
        { path: "company.hours", label: text("Часы работы компании", "Компания жұмыс уақыты", "Company business hours"), max: 1500, hint: text("Расписание ответов самого ИИ настраивается отдельно в управлении ИИ.", "ЖИ жауап кестесі басқару бөлімінде бөлек бапталады.", "AI reply hours are configured separately in AI controls.") },
      ])}
      {step === 2 && <><div className="ai-setup-card-list">{draft.offerings.map((item, index) => <div className="ai-setup-item" key={item.id}><div className="ai-setup-item-head"><b>{item.name || `${text("Предложение", "Ұсыныс", "Offer")} ${index + 1}`}</b>{removeButton("offerings", index)}</div>{fields([
        { path: `offerings.${index}.name`, label: text("Название", "Атауы", "Name"), short: true, max: 300, required: true },
        { path: `offerings.${index}.description`, label: text("Что это и кому подходит?", "Бұл не және кімге арналған?", "What is it and who is it for?"), required: true },
        { path: `offerings.${index}.price`, required: selectedRoles.includes("sales"), label: text("Цена и порядок расчёта", "Баға және есептеу тәртібі", "Price and calculation"), max: 1000, hint: text("Укажите валюту, фиксированную цену / «от» / индивидуальный расчёт. Например: от 150 000 ₸, итог после оценки задачи.", "Валютаны, нақты / бастапқы бағаны немесе жеке есептеуді жазыңыз.", "Include currency and fixed, starting or custom pricing. Example: from 150,000 KZT, quoted after scope review.") },
        { path: `offerings.${index}.includes`, label: text("Что входит в стоимость?", "Бағаға не кіреді?", "What is included?"), max: 2000 },
        { path: `offerings.${index}.timing`, label: text("Сроки", "Мерзімдер", "Timeframes"), max: 1000 },
        { path: `offerings.${index}.restrictions`, label: text("Что не входит и какие ограничения?", "Не кірмейді және қандай шектеу бар?", "Exclusions and restrictions"), max: 2000 },
      ])}</div>)}</div>{!draft.offerings.length && <p className="ai-setup-guidance">{text("Добавьте услуги, о которых ИИ сможет рассказать клиенту.", "ЖИ клиентке түсіндіретін қызметтерді қосыңыз.", "Add the services AI can describe to customers.")}</p>}<button className="btn secondary ai-setup-add" disabled={draft.offerings.length >= 30} onClick={() => edit("offerings", [...draft.offerings, { id: crypto.randomUUID(), name: "", description: "", price: "", includes: "", timing: "", restrictions: "" }])}>+ {text("Добавить услугу или товар", "Қызмет немесе тауар қосу", "Add service or product")}</button></>}
      {step === 3 && <><AiGoalPicker draft={draft} onChange={value => edit("conversation", value)} /><div className="ai-setup-guidance">{selectedRoles.map(role => <div key={role}><b>{roles[role][0]}: </b>{roles[role][1]}</div>)}{selectedRoles.includes("booking") && <p>{text("ИИ собирает запрос на запись. Свободное время и саму запись подтверждает сотрудник; календарь этим мастером не подключается.", "ЖИ жазылу өтінішін жинайды. Бос уақыт пен жазылуды қызметкер растайды; шебер күнтізбе қоспайды.", "AI collects booking requests. Staff confirms availability and bookings; this wizard does not connect a calendar.")}</p>}</div>{fields([
        { path: "conversation.goal", label: text("Какую главную задачу должен решить ИИ?", "ЖИ қандай басты міндетті шешуі керек?", "What outcome should AI achieve?"), max: 2000, required: true, hint: draft.primaryRole === "sales" ? text("Например: подобрать услугу и договориться о звонке с менеджером.", "Мысалы: қызмет таңдап, менеджермен қоңырау келісу.", "Example: recommend a service and agree on a sales call.") : text("Опишите конкретный результат, который полезен клиенту и компании.", "Клиент пен компанияға пайдалы нақты нәтижені сипаттаңыз.", "Describe a concrete outcome useful to the customer and company.") },
        { path: "conversation.questions", label: text("Что нужно узнать у клиента?", "Клиенттен нені білу керек?", "What should AI ask the customer?"), required: selectedRoles.some(role => role === "qualification" || role === "booking" || role === "sales"), hint: text("По одному пункту на строку: задача, срок, бюджет, город. Для записи — услуга, желаемые дата и время, контакт.", "Әр жолға бір тармақ: міндет, мерзім, бюджет, қала. Жазылуға — қызмет, күн, уақыт, байланыс.", "One item per line: need, deadline, budget, location. For booking: service, preferred time and contact.") },
        { path: "conversation.completion", required: true, label: text("Что делать после выяснения задачи?", "Міндет анықталғанда не істеу керек?", "What is the next step?"), max: 2000, hint: text("Например: кратко подтвердить потребность и передать сотруднику для расчёта.", "Мысалы: қажеттілікті қысқаша растап, есептеу үшін қызметкерге беру.", "Example: summarize the need and pass to staff for a quote.") },
        { path: "conversation.successCriteria", label: text("Как понять, что задача выполнена?", "Міндет орындалғанын қалай білеміз?", "How will you know the task is complete?"), required: true, max: 2000, hint: text("Например: клиент выбрал услугу, подтвердил объём и согласился на расчёт у менеджера.", "Мысалы: клиент қызмет пен көлемді таңдап, менеджердің есебіне келісті.", "Example: the customer chose a service, confirmed the scope and agreed to a staff quote.") },
        { path: "conversation.benefits", label: text("Какие преимущества можно упоминать?", "Қандай артықшылықтарды айтуға болады?", "Which benefits can AI mention?"), max: 3000, hint: text("Только подтверждённые факты и реальные примеры.", "Тек расталған деректер мен нақты мысалдар.", "Only verified facts and real examples.") },
        ...(selectedRoles.includes("sales") ? [{ path: "conversation.objections", label: text("Как отвечать на сомнения и возражения?", "Күмән мен қарсылыққа қалай жауап беру керек?", "How should AI handle objections?"), hint: text("Например: «Дорого» → объяснить состав работы, предложить меньший объём. Скидку не обещать.", "Мысалы: «Қымбат» → жұмыс құрамын түсіндіріп, аз көлем ұсыну. Жеңілдік уәде етпеу.", "Example: 'Too expensive' → explain the scope or offer a smaller scope, without promising discounts.") }] : []),
      ])}</>}
      {step === 4 && fields([
        { path: "terms.payment", label: text("Как проходит оплата?", "Төлем қалай жасалады?", "How does payment work?"), max: 2500, hint: text("Предоплата, этапы, способы оплаты. Не указывайте данные карт.", "Алдын ала төлем, кезеңдер, төлеу тәсілдері. Карта деректерін жазбаңыз.", "Deposits, milestones and payment methods. Do not include card details.") },
        { path: "terms.delivery", label: text("Как передаётся результат или доставляется товар?", "Нәтиже немесе тауар қалай жеткізіледі?", "How is the result or product delivered?"), max: 2500 },
        { path: "terms.guarantees", label: text("Какие гарантии действуют?", "Қандай кепілдік бар?", "What guarantees apply?"), max: 2500 },
        { path: "terms.cancellation", label: text("Правила отмены и возврата", "Бас тарту және қайтару шарттары", "Cancellation and refund rules"), max: 2500 },
        { path: "terms.discounts", label: text("Когда допустимы скидки?", "Жеңілдік қашан беріледі?", "When are discounts allowed?"), max: 2500, hint: text("Например: только по согласованию с менеджером.", "Мысалы: тек менеджер келісімімен.", "Example: only with a manager's approval.") },
      ])}
      {step === 5 && <><h4>{text("Частые вопросы", "Жиі қойылатын сұрақтар", "Frequently asked questions")}</h4><div className="ai-setup-card-list">{draft.faq.map((item, i) => <div className="ai-setup-item" key={item.id}><div className="ai-setup-item-head"><b>{text("Вопрос", "Сұрақ", "Question")} {i + 1}</b>{removeButton("faq", i)}</div>{fields([{ path: `faq.${i}.question`, label: text("Что спрашивает клиент?", "Клиент не сұрайды?", "What does the customer ask?"), short: true, max: 1000, required: true }, { path: `faq.${i}.answer`, label: text("Как правильно ответить?", "Қалай дұрыс жауап беру керек?", "What is the approved answer?"), required: true }])}</div>)}</div><button className="btn secondary ai-setup-add" disabled={draft.faq.length >= 40} onClick={() => edit("faq", [...draft.faq, { id: crypto.randomUUID(), question: "", answer: "" }])}>+ {text("Добавить вопрос и ответ", "Сұрақ пен жауап қосу", "Add a question and answer")}</button>
      <div className="ai-setup-subsection"><h4>{text("Материалы компании", "Компания материалдары", "Company materials")}</h4><p>{text("Здесь также находятся ранее опубликованные материалы. Проверьте актуальность цен и условий.", "Мұнда бұрын жарияланған материалдар да бар. Баға мен шарттардың өзектілігін тексеріңіз.", "Previously published material is included here. Check that prices and terms are current.")}</p><div className="ai-setup-card-list">{draft.knowledge.map((item, i) => <div className="ai-setup-item" key={item.id}><div className="ai-setup-item-head"><b>{item.title || `${text("Материал", "Материал", "Material")} ${i + 1}`}</b>{removeButton("knowledge", i)}</div>{fields([{ path: `knowledge.${i}.title`, label: text("Название материала", "Материал атауы", "Material title"), short: true, max: 300, required: true }, { path: `knowledge.${i}.content`, label: text("Содержание", "Мазмұны", "Content"), max: 65000, required: true }])}</div>)}</div><button className="btn secondary ai-setup-add" disabled={draft.knowledge.length >= 40} onClick={() => edit("knowledge", [...draft.knowledge, { id: crypto.randomUUID(), title: "", content: "" }])}>+ {text("Добавить материал", "Материал қосу", "Add material")}</button></div></>}
      {step === 6 && <>{fields([{ path: "conversation.assistantName", label: text("Как представляется помощник?", "Көмекші өзін қалай таныстырады?", "How should the assistant introduce itself?"), short: true, max: 150, hint: text("Например: помощник CreoLab. Можно оставить пустым.", "Мысалы: CreoLab көмекшісі. Бос қалдыруға болады.", "Example: CreoLab assistant. Optional.") }])}<label className="ai-setup-field" style={{ margin: "20px 0" }}>{text("Тон общения", "Қарым-қатынас мәнері", "Tone of voice")}<select value={draft.conversation.style} onChange={e => edit("conversation.style", e.target.value)}><option value="friendly">{text("Доброжелательный", "Жылы жүзді", "Friendly")}</option><option value="business">{text("Деловой", "Іскерлік", "Businesslike")}</option><option value="concise">{text("Краткий и конкретный", "Қысқа әрі нақты", "Concise")}</option></select></label>{fields([
        { path: "conversation.greeting", label: text("Предпочтительное приветствие", "Қалаулы сәлемдесу", "Preferred greeting"), max: 1000, hint: text("Используется в начале разговора. Язык — русский или казахский по сообщению клиента.", "Әңгіме басында қолданылады. Тіл — клиент хабарламасына қарай орысша не қазақша.", "Used at the start of a conversation, in Russian or Kazakh to match the customer.") },
        { path: "handoff.when", label: text("Когда обязательно нужна помощь сотрудника?", "Қызметкер көмегі қашан міндетті?", "When should staff take over?"), max: 2000, hint: text("Например: индивидуальный расчёт, жалоба, нестандартная задача. Запрос клиента на человека имеет приоритет.", "Мысалы: жеке есеп, шағым, ерекше міндет. Клиенттің адаммен сөйлесу өтініші басым.", "Example: a custom quote, complaint or unusual request. Requests for a person take priority.") },
        { path: "handoff.contact", label: text("Кому передать вопрос и как связаться?", "Сұрақты кімге және қалай беру керек?", "Who can help and how can they be reached?"), max: 1000 },
      ])}<p className="ai-setup-help">{text("Распределение по сотрудникам и автоматические причины передачи задаются в управлении ИИ. Эти ответы дополняют инструкции.", "Қызметкерлерге бөлу және автоматты беру себептері ЖИ басқаруда бапталады. Бұл жауаптар нұсқаулықты толықтырады.", "Staff assignment and automatic handoff rules are set in AI controls. These answers add business instructions.")}</p><details className="ai-setup-disclosure"><summary>{text("Дополнительные инструкции и прежний промпт", "Қосымша нұсқаулық және бұрынғы промпт", "Additional instructions and previous prompt")}</summary><p className="ai-setup-help">{text("Существующий промпт сохранён здесь. Уберите из него устаревшие или противоречащие анкете правила.", "Бұрынғы промпт осында сақталды. Ескірген немесе анкетаға қайшы ережелерді жойыңыз.", "The previous prompt is retained here. Remove outdated rules or conflicts with the questionnaire.")}</p>{fields([{ path: "additionalInstructions", label: text("Уточнения владельца", "Иесінің нақтылаулары", "Owner's additional instructions"), max: 60000 }])}</details></>}
      {step === 7 && <><div className={`ai-setup-readiness ${compiled.issues.length ? "needs-attention" : ""}`}><h4>{blockers.length ? text("Нужно заполнить перед запуском", "Іске қосу алдында толтыру керек", "Complete these before publishing") : text("Обязательные сведения заполнены", "Міндетті ақпарат толтырылған", "Required information is complete")}</h4><p>{text("Проверены обязательные поля, повторы вопросов и размер материалов. Достоверность сведений и противоречия в свободном тексте нужно проверить вам.", "Міндетті өрістер, сұрақ қайталануы және материал көлемі тексерілді. Деректер мен еркін мәтіндегі қайшылықтарды өзіңіз тексеріңіз.", "Required fields, duplicate entries and content size are checked. Please verify facts and contradictions in free text yourself.")}</p>{compiled.issues.length > 0 && <ul>{compiled.issues.map((issue, i) => <li key={i}><button type="button" onClick={() => go(stepFor(issue.field))}>{issueLabel(issue)}</button></li>)}</ul>}</div>
      <div className="ai-setup-summary"><div><small>{text("Главная функция", "Негізгі міндет", "Primary function")}</small><b>{roles[draft.primaryRole][0]}</b></div><div><small>{text("Материалы для ответов", "Жауап материалдары", "Knowledge entries")}</small><b>{compiled.knowledge.length}</b></div></div>
      <details className="ai-setup-disclosure"><summary>{text("Посмотреть сформированные инструкции", "Құрастырылған нұсқаулықты көру", "View generated instructions")}</summary><pre>{compiled.prompt}</pre></details><details className="ai-setup-disclosure"><summary>{text("Посмотреть базу знаний", "Білім базасын көру", "View generated knowledge")}</summary>{compiled.knowledge.map((item, i) => <div key={i}><h4>{item.title}</h4><pre>{item.content}</pre></div>)}</details>
      <div className="ai-setup-summary"><div><small>{text("Цель", "Мақсат", "Goal")}</small><b>{draft.conversation.goal}</b></div><div><small>{text("Критерий результата", "Нәтиже өлшемі", "Success criteria")}</small><b>{draft.conversation.successCriteria || "—"}</b></div></div>
      <AiSetupQualityChecks key={state.revision} state={state} disabled={!allowed || dirty || blockers.length > 0 || busy || testing} onState={setState} onBusy={setTesting} />
      <details className="ai-setup-disclosure"><summary>{text("Свободный тестовый диалог", "Еркін сынақ диалогы", "Free-form test conversation")}</summary><div className="ai-setup-chat"><div className="ai-setup-chat-head"><div><b>{text("Тестовый диалог", "Сынақ диалогы", "Test conversation")}</b><p>{text("Проверяет сохранённый черновик. Клиентам ничего не отправляется. Используются AI-кредиты вашего тарифа.", "Сақталған жобаны тексереді. Клиентке хабар жіберілмейді. Тарифтің AI-кредиттері жұмсалады.", "Tests the saved draft without sending customer messages. Uses your plan's AI credits.")}</p></div><button className="btn secondary" onClick={() => { setChat([]); setHandedOff(false); }} disabled={testing || !chat.length}>{text("Сначала", "Қайта бастау", "Restart")}</button></div><div className="ai-setup-chat-log" ref={chatRef} role="log" aria-live="polite">{!chat.length && <p className="ai-setup-chat-empty">{text("Напишите как клиент: спросите цену, сроки или опишите задачу.", "Клиент ретінде жазыңыз: баға, мерзім сұраңыз не міндетті сипаттаңыз.", "Write as a customer: ask about prices, timelines or describe a need.")}</p>}{chat.map((item, i) => <p key={i} className={`ai-setup-chat-message ${item.role === "user" ? "is-user" : ""}`}><small>{item.role === "user" ? text("Вы — клиент", "Сіз — клиент", "You as customer") : text("ИИ", "ЖИ", "AI")}</small>{item.content}</p>)}</div><div className="ai-setup-chat-compose"><textarea aria-label={text("Тестовое сообщение клиента", "Клиенттің сынақ хабары", "Test customer message")} value={message} maxLength={4000} onChange={event => setMessage(event.target.value)} disabled={!canTest} placeholder={text("Здравствуйте! Сколько стоят ваши услуги?", "Сәлеметсіз бе! Қызметтеріңіз қанша тұрады?", "Hello! What do your services cost?")} /><button className="btn" disabled={!canTest || !message.trim()} onClick={() => void testReply()}>{testing ? text("ИИ отвечает…", "ЖИ жауап беруде…", "AI is replying…") : text("Проверить ответ", "Жауапты тексеру", "Test reply")}</button></div>{(!canTest && !busy || handedOff) && <p className="ai-setup-guidance">{dirty ? text("Сохраните черновик перед тестом.", "Сынақ алдында жобаны сақтаңыз.", "Save the draft before testing.") : blockers.length ? text("Заполните обязательные поля, указанные выше.", "Жоғарыдағы міндетті өрістерді толтырыңыз.", "Complete the required fields above.") : !allowed ? text("Для теста и публикации нужен тариф с ИИ-менеджером.", "Сынақ пен жариялау үшін ЖИ-менеджер тарифі қажет.", "Testing and publishing require an AI manager plan.") : text("Начните новый тестовый диалог.", "Жаңа сынақ диалогын бастаңыз.", "Start a new test conversation.")}</p>}</div>
      </details><div className="ai-setup-publish"><h4>{text("Применить к ответам клиентам", "Клиент жауаптарына қолдану", "Apply to customer replies")}</h4><p>{text("Инструкции и база знаний публикуются вместе. Аудитория, расписание и диалоги сотрудников сохраняют свои настройки.", "Нұсқаулық пен білім бірге жарияланады. Аудитория, кесте және қызметкер диалогтары өз баптауын сақтайды.", "Instructions and knowledge publish together. Audience, schedule and staff conversations keep their settings.")}</p><label className="ai-setup-check"><input type="checkbox" checked={approved} onChange={event => setApproved(event.target.checked)} />{text("Я проверил сведения, цены и условия", "Ақпаратты, бағаны және шарттарды тексердім", "I have checked the facts, prices and terms")}</label><button className="btn" style={{ marginTop: 16 }} disabled={!allowed || dirty || blockers.length > 0 || !approved || !state.quality?.ready || state.liveChanged || !state.hasDraftChanges} onClick={() => void publish()}>{text("Опубликовать настройки", "Баптауларды жариялау", "Publish settings")}</button>{dirty && <p>{text("Сначала сохраните черновик.", "Алдымен жобаны сақтаңыз.", "Save the draft first.")}</p>}{!state.quality?.ready && <p>{text("Завершите обязательные сценарии выше и сохраните свою оценку ответов.", "Жоғарыдағы міндетті сценарийлерді аяқтап, жауап бағасын сақтаңыз.", "Complete the required scenarios above and save your reviews.")}</p>}{state.publishedAt && <p>{text("Последняя публикация", "Соңғы жариялау", "Last published")}: {new Date(state.publishedAt).toLocaleString(locale === "kk" ? "kk-KZ" : locale === "en" ? "en-GB" : "ru-RU")}</p>}{state.activation && <p>{state.activation.prompt?.reason || state.activation.note}</p>}</div>
      {!!state.versions.length && <details className="ai-setup-disclosure"><summary>{text("История версий и восстановление", "Нұсқа тарихы және қалпына келтіру", "Version history and restore")}</summary><div className="ai-setup-versions">{state.versions.map(version => <div className="ai-setup-version" key={version.id}><div><b>{version.label}</b><small>{new Date(version.createdAt).toLocaleString()} {version.current ? `· ${text("Действует", "Қолданыста", "Live")}` : ""}</small></div>{!version.current && <button className="btn secondary" disabled={dirty || state.liveChanged || !allowed} onClick={() => { setConfirm({ action: "restore", versionId: version.id }); }}>{text("Восстановить", "Қалпына келтіру", "Restore")}</button>}</div>)}</div></details>}
      </>}
    </fieldset><div className="ai-setup-step-footer"><button className="btn secondary" disabled={step === 0} onClick={() => go(step - 1)}>{text("Назад", "Артқа", "Back")}</button><button className="btn" disabled={step === steps.length - 1} onClick={() => go(step + 1)}>{text("Далее", "Келесі", "Next")}</button></div>
    {dirty ? <div className="ai-setup-savebar"><div><b>{text("Ответы ещё не сохранены", "Жауаптар сақталмаған", "Unsaved answers")}</b><small>{text("Можно сохранить и продолжить позже", "Сақтап, кейін жалғастыруға болады", "Save and continue later")}</small></div><div className="actions"><button className="btn secondary" disabled={busy || testing} onClick={() => { setDraft(state.draft); setChat([]); setApproved(false); }}>{text("Сбросить изменения", "Өзгерістерді қайтару", "Discard changes")}</button><button className="btn" disabled={busy || testing} onClick={() => void save()}>{busy ? text("Сохраняем…", "Сақталуда…", "Saving…") : text("Сохранить черновик", "Жобаны сақтау", "Save draft")}</button></div></div> : <p className="ai-setup-saved">{text("Черновик сохранён. Изменения действуют только после публикации.", "Жоба сақталған. Өзгерістер тек жариялаудан кейін күшіне енеді.", "Draft saved. Changes apply only after publishing.")}</p>}
    </div></div>
  </section>;
}
